sudo: required
language: java
services:
- docker
before_install:
- mkdir /tmp/build
- docker pull qcifengineering/redbox-ant-builder
- docker run -v /tmp/build:/build -e "CLONEPATH=https://github.com/redbox-mint-contrib/andsrifcs2maven.git"
  qcifengineering/redbox-ant-builder
install: true
script: true
after_success:
- docker run -v /tmp/build:/build -e "SONATYPE_USERNAME=$SONATYPE_USERNAME" -e "SONATYPE_PASSWORD=$SONATYPE_PASSWORD"
  qcifengineering/redbox-builder /bin/bash -c "cd build/src;mvn --settings /m2_repo/travis-settings.xml
  -Dmaven.repo.local=/m2_repo -DskipTests=true deploy"
env:
  global:
  - ANT_OPTS=-Dfile.encoding=UTF-8
  - secure: XGxREPCGY5TtXETmiydUjG938tgnwADLnawUyoE8qd25thyu79zdRSxHInB9xK6pykJI1KGhyAh6wL7jLyopOUJ1cY4ocauATrz27NlKbdAzbXjOBmBNlWr2T5dcsaY0f8fhmxyJcRxr+A1aD3ZwUNG9p20KmuMUphtbj+SHg+rIcQW5EPFVU8N3/rY9eXV1JuTagrZiXXKZubKnCX1Sid2xTy1I+cSurP/MtrOfIfX5fSSquBfDUfpqFtha0hiODnKMRHtcz2uZSVWRucH3gl4Z/IVOPwEaWRSlf6jyFAmmH6InVFOmJCVPVj2endAlenC9aKh156j1Yd2FaZ4cJAERoiF9EsS16QAu5M8ErTEnYKa/UVaXOBS+oMJGLK7dlnXmyUxw9dXuRIUCklCS7FOZlfJIaGpkA/ic3ny6l8+xzKE9U6dyuiq2zo8EatRC8RDU82BxhDAFZCpd7tjED9biSvqEmFSK3x2GMaGq73ssgKPeQt3z0lzISqLLhCX3ov2MZmg2ofvBajySw38H3tBr+1j0a0mKfgLhnNt9SMDzkQeZyRDGvZOlwYcNq3I3zoqmVnq2e9FVnaRewuyicv7Ot5RbWb4cpWB+WRqtULLu1QEDGNUhyIABb7ZEwP8h43KTPwUpR4hJ16K8sWmwkYhxlJmIQqpkgAM0LgoSVlw=
  - secure: RUGvALEnYmbj5/JJT800G/a+HUNzFdUJadcedWamGjL55MJ8W2ZuAVO68LK/F2m5XuLGHNhAUAOeL3+yFmGxJpnnn0zjA6yfHgZiOiWzRgR7v4X5LDjW3jewtghQ2ge9dDqihhjaOGtZO2Dx5BmZgdKeDu9sryrlLM5FIHQsV2nsXNdh3WXFj1S0ODz9L62NPtGtVGH9s9xxVkHvGsFsQ0BzdDhCJXoX5hIPtAsQBWwHGJMst2CLBFOQtTBr5oRG50nMrTcoUdXL8TQzjTcWQEg84kLyBg5z9DIkb0Y5RCcKspW6DNPle6i1paiYKgw2dZ8QPG3Ek7MQQfbz71o02sIjXjMpok1ABYzFfOJJQnzPD1mf7GfsIF1kyJ+9rLvY+Q4yj6RVs5CecACipyiX5LOLKUCZ2Yc65jiEKOwz6SOk1V2OvdRzjG7OAg6oQkfe5UI8JYvzgGpbLpYA0yWq7dHL9uxz5v4PW5UO9cMm/kt2+tqEsDzi3aUkyU6sou/4W0IsSVB2HOZicTMytkbs2bR/0kvxMrIObAE5qSgXgUn9eBFyCHfs2PowI7lWJpsC3Ryx0BvXgA3Xvy4vRNlicWwLQspA4h+UgqmizxtAUfF32V3R/IydQmBxCy5Ys8oFnLcLgOCvQGTgNw8FODOsRX4qTOVEkI73mP96jrIi16Q=
